### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by chenhch8** [thunlp/GEAR#10]
你好，请问从哪里可以下载到GEAR的预训练模型？

**Comment by jayzzhou-thu** [comment]
可以参考我们的BERT-Pair模型（readme中有下载方法），我们最终的特征提取就是基于它的。

**Comment by FayeXXX** [comment]
你好，非常感谢你分享的这份优雅的代码，简单易读。这个gear推理部分是不是把BERT embedding取出来，然后跑了一层self-attention？

**Comment by jayzzhou-thu** [comment]
> 你好，非常感谢你分享的这份优雅的代码，简单易读。这个gear推理部分是不是把BERT embedding取出来，然后跑了一层self-attention？

你好，感谢关注。简单来说是这样的，但是我们是从GNN的视角出发，具体的实现上我们的attention是和transformer里的self-attention是有一些区别的，以及我们通过GNN的层数来选择attention的层数。

**Comment by FayeXXX** [comment]
谢谢你的及时回复哈~还有几个疑问想请教一下：
0.同一个claim的5个evidence之间是什么关系呀？
1.max_seq_length=128，但是evidence中很多长度超过128，这样evidence信息就损失了呢？但就算损失了，你的模型效果确实非常好
2.GNN可以直接加在bert上一起finetune吗？
3.KGAT的工作关注细粒度的kernel，但是并没看懂。细粒度的信息有没有简单的方法可以做呢？

**Comment by jayzzhou-thu** [comment]
> 谢谢你的及时回复哈~还有几个疑问想请教一下：
> 0.同一个claim的5个evidence之间是什么关系呀？
> 1.max_seq_length=128，但是evidence中很多长度超过128，这样evidence信息就损失了呢？但就算损失了，你的模型效果确实非常好
> 2.GNN可以直接加在bert上一起finetune吗？
> 3.KGAT的工作关注细粒度的kernel，但是并没看懂。细粒度的信息有没有简单的方法可以做呢？

0. 同一个claim的5个evidence是根据置信度独立抽取出来的，他们之间没有逻辑关系
1. 确实会有损失的情况出现，我们是根据evidence的平均长度设置的参数，所以能够保证绝大多数的样例
2. 可以，KGAT中汇报的的结果应该就是一起finetune得到的
3. 感觉细粒度直观上就是考虑词与词之间的注意力，KGAT中应该是使用BERT学习的词与词之间的注意力，然后在这上面套了一层Kernel
