### ISSUE TITLE
您好，document retrieval的步骤我似乎并没有发现，请问您是怎么做的呢？

### ISSUE THREAD

**Issue by eyuansu62** [thunlp/GEAR#11]

**Comment by jayzzhou-thu** [comment]
您好，这个论文中有提到，我们是复现的Athene UKP TU Darmstadt队伍参加比赛时的方法。
他们的论文 https://arxiv.org/pdf/1809.01479.pdf
代码 https://github.com/UKPLab/fever-2018-team-athene

**Comment by eyuansu62** [comment]
您好，他们是用tf-idf匹配的嘛 因为我在里面没有找到具体的步骤

**Comment by jayzzhou-thu** [comment]
@eyuansu62 首先使用allennlp的工具对claim进行成分分析，使用其中的名词短语、动词前所有单词以及整个句子作为搜索词，使用MediaWiki的API查询文档，然后选出排名比较高的几个。在上述论文里的3.1节里有介绍。
