### ISSUE TITLE
403forbiden

### ISSUE THREAD

**Issue by WhynotLei** [thunlp/GEAR#19]
你好！
# Download the fever database
wget -O data/fever/fever.db https://s3-eu-west-1.amazonaws.com/fever.public/wiki_index/fever.db
下载数据时报错:
Connecting to s3-eu-west-1.amazonaws.com (s3-eu-west-1.amazonaws.com)|52.218.25.219|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-03-23 23:04:59 ERROR 403: Forbidden.
试了很多办法无法解决

**Comment by jayzzhou-thu** [comment]
您好，应该是FEVER作者提供的下载链接失效了。您可以去原来的repo (https://github.com/sheffieldnlp/naacl2018-fever) 使用里面的代码重新构建一份fever.db文件。

把原repo下载之后，运行下方脚本即可。
`bash scripts/download-raw-wiki.sh`
`bash scripts/process-wiki.sh`

处理过程需要花费一段时间，最终的fever.db文件大概有9GB。希望能解决您的问题。
