### ISSUE TITLE
train.ensembles.s10.jsonl broken

### ISSUE THREAD

**Issue by tbright17** [thunlp/GEAR#2]
Hi,

Thanks for the sharing the code. During running retrieval_to_bert_input.py, I found the file train.ensembles.s10.jsonl broken was broken. The last line is

`{"id": 105959, "verifiable": "VERIFIABLE", "label": "REFUTES", "claim": "Julie Christie was nominated for an Oscar for the 2004 film Afterglow.", "evidence": [[[124380, 138737, "Julie_Christie", 12]]], "noun_phrases": ["an Oscar", "Julie Christie", "Julie Christie was nominated for`

which can't be loaded by json. Please check.

Thanks

**Comment by jayzzhou-thu** [comment]
I checked the file on the web and found it is complete. Please check if your file is damaged.

**Comment by tbright17** [comment]
Thanks for the reply. Asked a friend in China to download for me, and it works now.

**Comment by p-null** [comment]
> Thanks for the reply. Asked a friend in China to download for me, and it works now.

Can you tell what's wrong with your first run? I have the same issue as yours. Thanks.

OS: Ubuntu 16.04
Python: 3.7.4

**Comment by p-null** [comment]
> I checked the file on the web and found it is complete. Please check if your file is damaged.

Hi, just wanna report the same issue here.
```
...
144000
145000
Traceback (most recent call last):
  File "retrieval_to_bert_input.py", line 123, in <module>
    process('../data/retrieved/train.ensembles.s10.jsonl', '../data/bert/bert-nli-train-retrieve-set.tsv')
  File "retrieval_to_bert_input.py", line 19, in process
    object = json.loads(line.decode(ENCODING).strip('\r\n'))
  File "/root/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/root/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/anaconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 1028 (char 1027)
```
I tried to both files from THU cloud and google cloud, giving the same errors.
I am not sure what's wrong. Can anyone give a hint how did you solve this issue?

OS: Ubuntu 16.04
Python: 3.7.4

**Comment by jayzzhou-thu** [comment]
@tingkai-zhang 
My environment is Ubuntu 16.04 with Python 3.6.8. 
I think you can check if your file is complete with 145449 lines.
If you still have the problem, I can send you the file by email.

**Comment by p-null** [comment]
Upate: I re-dowloaded it from google cloud, it works now.
Thanks.

**Comment by eyuansu62** [comment]
不知道您解决这个问题了吗?我也是这一行出现了问题

**Comment by tbright17** [comment]
> 不知道您解决这个问题了吗?我也是这一行出现了问题

可能是清华云的下载有点问题，作者已经上传到google drive了 #3
