### ISSUE TITLE
Unable to download the fever database and issue in requirements file

### ISSUE THREAD

**Issue by amanagr6697** [thunlp/GEAR#20]
Please provide an alternative link to download the database there are issues in the requirements.txt file, it is not getting downloaded successfully.
Thankyou

**Comment by jayzzhou-thu** [comment]
Hi, the download link provided by the authors of  FEVER is unavailable now.  You can go to the original repo (https://github.com/sheffieldnlp/naacl2018-fever) and try to build the fever.db file by yourself according to its README.

That is to run 
`bash scripts/download-raw-wiki.sh`
`bash scripts/process-wiki.sh`
after you clone the repo.

The process takes time and the fever.db file is about 9GB. Hope this will help you.

**Comment by amanagr6697** [comment]
I also found an alternative way, i.e fever.ai/fever/fever.db and it's file size is approx 5 GB, do you think this would also work like intended?
Thanks for the early reply.

**Comment by jayzzhou-thu** [comment]
> I also found an alternative way, i.e fever.ai/fever/fever.db and it's file size is approx 5 GB, do you think this would also work like intended? Thanks for the early reply.

Hi, I am not quite sure because I have not used it. It may be used for other tasks such as FEVER 2.0.  To reproduce the results in this repo, I think it is better to rebuild the file from scratch.

**Comment by amanagr6697** [comment]
Unable to run bash scripts/process-wiki.sh file 
In build_tfidf.py there is this line 'from drqascripts.retriever.build_tfidf import *' which isn't able to resolve so I cloned this repo: https://github.com/j6mes/DrQA
and changed it to from DrQA.scripts.retriever.build_tfidf import * to make it work but then it is unable to parse TfIdfBuilder corresponding to the line 'tfidf_builder = TfIdfBuilder(args,'sqlite', {'db_path': args.db_path})'

Would be grateful for a solution.

**Comment by jayzzhou-thu** [comment]
> https://github.com/j6mes/DrQA

I guess you can try this:
`git+git://github.com/j6mes/drqa@parallel`
or just clone the repo and change to the parallel branch manually to install it.
`git checkout parallel`

**Comment by amanagr6697** [comment]
So, after processing things, I saw a GPU requirement for the process, and since my laptop doesn't have GPU, it's pretty cumbersome to go along that way... So, if you have a pre-trained model for the paper, can you give me that, along with instructions on how to predict it? Also, since my SSD is only 128GB, storage space is also running out...
So, it would be kind of you if you can provide me with that... Thanks again!

**Comment by amanagr6697** [comment]
Sir, so I did everything and got the files... Now, ig the model would be corresponding to best.pth.tar file in outputs folder, how to use that data.pkl file to predict accept/refuted by passing a sentence... Can you please provide info on this... This would be my last query, thanks a lot.
Thanks!!!

**Comment by amanagr6697** [comment]
Or tell me, where is the model stored and how can I use it to predict if it's not data.pkl in outputs best path folder.

**Comment by WhynotLei** [comment]
> 我还找到了另一种方法，即 fever.ai/fever/fever.db，它的文件大小约为 5 GB，您认为这也能按预期工作吗？ 感谢您的早期回复。

Hi, how do you get fever.ai/fever/fever.db? Can you tell me the method? Thank you very much.

**Comment by amanagr6697** [comment]
> > 我还找到了另一种方法，即 fever.ai/fever/fever.db，它的文件大小约为 5 GB，您认为这也能按预期工作吗？ 感谢您的早期回复。
> 
> Hi, how do you get fever.ai/fever/fever.db? Can you tell me the method? Thank you very much.

Go by the method they provided, fever.db would be generated at the designated folder, and then you can proceed normally...
