### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by eyuansu62** [thunlp/GEAR#4]
git+git://github.com/j6mes/drqa@parallel
git+git://github.com/sheffieldnlp/fever-scorer@master
这两个是不是无法git了呀

**Comment by jayzzhou-thu** [comment]
@eyuansu62 我试了一下pip install -r requirements.txt 是可以的，有相应的错误日志吗？

**Comment by eyuansu62** [comment]
Collecting git+git://github.com/j6mes/drqa@parallel (from -r requirements.txt (line 3))
&nbsp; Cloning git://github.com/j6mes/drqa (to revision parallel) to /tmp/pip-req-build-n5vybbhi
&nbsp; Running command git clone -q git://github.com/j6mes/drqa /tmp/pip-req-build-n5vybbhi
&nbsp; fatal: The remote end hung up unexpectedly
ERROR: Command errored out with exit status 128: git clone -q git://github.com/j6mes/drqa /tmp/pip-req-build-n5vybbhi Check the logs for full command output.

请问这是为什么呢？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"jayzzhou-thu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月23日(星期三) 晚上8:53
收件人:&nbsp;"thunlp/GEAR"<GEAR@noreply.github.com&gt;;
抄送:&nbsp;"末冬末秋"<772468951@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [thunlp/GEAR] hi (#4)




@eyuansu62 我试了一下pip install -r requirements.txt 是可以的，有相应的错误日志吗？

**Comment by jayzzhou-thu** [comment]
> Collecting git+git://github.com/j6mes/drqa@parallel (from -r requirements.txt (line 3)) &nbsp; Cloning git://github.com/j6mes/drqa (to revision parallel) to /tmp/pip-req-build-n5vybbhi &nbsp; Running command git clone -q git://github.com/j6mes/drqa /tmp/pip-req-build-n5vybbhi &nbsp; fatal: The remote end hung up unexpectedly ERROR: Command errored out with exit status 128: git clone -q git://github.com/j6mes/drqa /tmp/pip-req-build-n5vybbhi Check the logs for full command output. 请问这是为什么呢？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"jayzzhou-thu"<notifications@github.com&gt;; 发送时间:&nbsp;2019年10月23日(星期三) 晚上8:53 收件人:&nbsp;"thunlp/GEAR"<GEAR@noreply.github.com&gt;; 抄送:&nbsp;"末冬末秋"<772468951@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [thunlp/GEAR] hi (#4) @eyuansu62 我试了一下pip install -r requirements.txt 是可以的，有相应的错误日志吗？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

查一下问题可能在
fatal: The remote end hung up unexpectedly
这个可能有用 http://blog.fidding.me/article/87

**Comment by eyuansu62** [comment]
哦哦，谢谢您啦。 ------------------ 原始邮件 ------------------
发件人: "jayzzhou-thu"<notifications@github.com>
发送时间: 2019年10月23日(星期三) 晚上9:05
收件人: "thunlp/GEAR"<GEAR@noreply.github.com>;
抄送: "eyuansu62"<772468951@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [thunlp/GEAR] hi (#4)


 
Collecting git+git://github.com/j6mes/drqa@parallel (from -r requirements.txt (line 3)) &#xA0; Cloning git://github.com/j6mes/drqa (to revision parallel) to /tmp/pip-req-build-n5vybbhi &#xA0; Running command git clone -q git://github.com/j6mes/drqa /tmp/pip-req-build-n5vybbhi &#xA0; fatal: The remote end hung up unexpectedly ERROR: Command errored out with exit status 128: git clone -q git://github.com/j6mes/drqa /tmp/pip-req-build-n5vybbhi Check the logs for full command output. 请问这是为什么呢？
 …
 ------------------&#xA0;原始邮&#x4EF6;&#xA0;------------------ 发&#x4EF6;人:&#xA0;"jayzzhou-thu"<notifications@github.com>; 发送时间:&#xA0;2019年10月23日(星期三) 晚上8:53 收&#x4EF6;人:&#xA0;"thunlp/GEAR"<GEAR@noreply.github.com>; 抄送:&#xA0;"末冬末秋"<772468951@qq.com>;"Mention"<mention@noreply.github.com>; 主题:&#xA0;Re: [thunlp/GEAR] hi (#4) @eyuansu62 我试了一下pip install -r requirements.txt 是可以的，有相应的错误日志吗？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
  
查一下问题可能在
 fatal: The remote end hung up unexpectedly
 这个可能有空 http://blog.fidding.me/article/87
 
&mdash;

**Comment by Yuanlim0919** [comment]
您好，不好意思打扰了。我在安装的过程中也遇到一样的问题。但上面提供说可能有解决办法的链接已经没办法开启了，想请问有其他的方法吗？谢谢

完整的指令和error message 如下：

Collecting git+git://github.com/j6mes/drqa@parallel (from -r requirements.txt (line 4))
  Cloning git://github.com/j6mes/drqa (to revision parallel) to c:\users\acer\appdata\local\temp\pip-req-build-usc5i35f
  Running command git clone -q git://github.com/j6mes/drqa 'C:\Users\acer\AppData\Local\Temp\pip-req-build-usc5i35f'
  fatal: unable to connect to github.com:
  github.com[0: 20.27.177.113]: errno=Unknown error

WARNING: Discarding git+git://github.com/j6mes/drqa@parallel. Command errored out with exit status 128: git clone -q git://github.com/j6mes/drqa 'C:\Users\acer\AppData\Local\Temp\pip-req-build-usc5i35f' Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q git://github.com/j6mes/drqa 'C:\Users\acer\AppData\Local\Temp\pip-req-build-usc5i35f' Check the logs for full command output.

**Comment by jayzzhou-thu** [comment]
> //github.com/j6mes/drqa

Hi，下面是一个可行的方法，可以试试

先将分支克隆到本地
git clone https://github.com/j6mes/DrQA.git

之后进入目录之后切换到parallel分支
git checkout parallel

之后手动安装一下
python setup.py develop

**Comment by Yuanlim0919** [comment]
感谢你的回复，我试试看这个方法

**Comment by Yuanlim0919** [comment]
Hi 您好，我尝试这个方法的过程中发生了这个错误：
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    readme = f.read()
  File "C:\Users\acer\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 18545: character maps to <undefined>

后来查到是 open() 里面需要代入encoding="utf8" 这个参数，在这边分享一下
https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character
