### ISSUE TITLE
同样的问题

### ISSUE THREAD

**Issue by eyuansu62** [thunlp/GEAR#5]
database disk image is malformed
145449 
 0%|                                                                  | 0/145449 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "retrieval_to_bert_input.py", line 123, in <module>
    process('../data/retrieved/train.ensembles.s10.jsonl', '../data/bert/bert-nli-train-retrieve-set.tsv')
  File "retrieval_to_bert_input.py", line 40, in process
    (utils.normalize(article),)
sqlite3.DatabaseError: database disk image is malformed
我也是那个文件的问题，不知道这是文件的问题吗？

**Comment by jayzzhou-thu** [comment]
@eyuansu62 你的问题其他人不一样，这里的提示是数据库文件出了问题，可以检查一下fever.db这个文件。

**Comment by eyuansu62** [comment]
但是我就是按照你的命令下的丫，他总提示有问题好奇怪
