### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by eyuansu62** [thunlp/GEAR#6]
145000
../data/retrieved/train.ensembles.s10.jsonl
145449
  7%|███▌                                                | 10000/145449 [00:08<02:06, 1073.78it/s]Error: cant find empty 0 for 10130
  7%|███▊                                                | 10507/145449 [00:08<01:37, 1381.50it/s]Error: cant find empty 0 for 10633
 13%|██████▋                                             | 18805/145449 [00:15<01:53, 1120.60it/s]Error: cant find empty 0 for 18963
 14%|███████▍                                            | 20926/145449 [00:16<01:23, 1494.50it/s]
我又从谷歌云盘上下载了文件 但是出现这个问题 不知道您知道为什么吗

**Comment by jayzzhou-thu** [comment]
这个是正常的，意思是从数据库中找不到 empty 文章的第0行（确实没有），不影响程序运行。

**Comment by eyuansu62** [comment]
那也就是说在 build_gear_input_set 时，出现Warning: 136160
Warning: 137826
Warning: 140457
Warning: 140716
Warning: 140956
Warning: 141076
这些也是相同的道理吗？

**Comment by jayzzhou-thu** [comment]
@eyuansu62  是的。具体输出的含义可以去看代码
