### ISSUE TITLE
BERT-Pair

### ISSUE THREAD

**Issue by Decalogue** [thunlp/GEAR#8]
您好!请问有预训练 BERT-Pair 的代码和数据吗?

**Comment by jayzzhou-thu** [comment]
有的，等我们整理后会放出。

**Comment by jayzzhou-thu** [comment]
hi @Decalogue BERT-Pair的代码和数据可以在这里被下载到～ 
https://cloud.tsinghua.edu.cn/d/b98d0aa9edf1407abe85/ 

如果有任何使用的问题欢迎提出。

**Comment by WhynotLei** [comment]
您好！这个链接已经关闭了，请问还有其他关于BERT-Pair的代码和数据的链接呢
