### ISSUE TITLE
请问evidence Graph 是怎么构建的?

### ISSUE THREAD

**Issue by shuaishuaij** [thunlp/GEAR#9]
请问evidence Graph 是怎么构建的? 是每一个短句算是一条evidence吗? 看上去因为直接用attention学习边的权值, 那个图到底是什么样子的呢? 论文里简单的提及了一下但没具体讲

**Comment by jayzzhou-thu** [comment]
> 请问evidence Graph 是怎么构建的? 是每一个短句算是一条evidence吗? 看上去因为直接用attention学习边的权值, 那个图到底是什么样子的呢? 论文里简单的提及了一下但没具体讲

您好，我们是将每一条证据和声明联合送进BERT进行表示学习，使用CLS Token的表示作为这一个证据-声明对的表示。然后对于所有的证据-声明对，我们使用了一个全连接的图来进行学习。

**Comment by shuaishuaij** [comment]
bert限制最大长度是512, evidence过长的情况下, 是取前509个词作为evidence吗? 会不会出现support的证据正好被裁掉的了情况?

**Comment by jayzzhou-thu** [comment]
> bert限制最大长度是512, evidence过长的情况下, 是取前509个词作为evidence吗? 会不会出现support的证据正好被裁掉的了情况?

确实会有您说的情况出现，实际中很短或者很长的evidence都会出现，但是数量不太多。我们对句子长度的平均情况进行了考虑然后选择了现在的参数。
